name: Install-Build-Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build nest app
        run: npm run build

  build-with-docker:
    name: Build Image and Push To ECR
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag & Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.short-sha.outputs.sha }}
        run: |
          docker build --file .docker/Dockerfile -t $ECR_REGISTRY/instamd-be-dev:$IMAGE_TAG .
          docker push $ECR_REGISTRY/instamd-be-dev:$IMAGE_TAG


  deploy-to-ecs:
    runs-on: ubuntu-latest
    needs: [build-with-docker]
    steps:
      - uses: actions/checkout@v2
      - uses: imranismail/setup-kustomize@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Populate Variables in Task Definition
        uses: nowactions/envsubst@v1
        with:
          input: ./.aws/develop/develop.json
          output: ./task-definition.json
        env:
          IMAGE: ${{ steps.login-ecr.outputs.registry }}/instamd-be-dev:${{ steps.short-sha.outputs.sha }}
          VERSION: ${{ steps.short-sha.outputs.sha }}
          GITHUB_REF: ${GITHUB_REF}
          GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}
          GITHUB_SHA: ${GITHUB_SHA}
          GITHUB_ACTION_REPOSITORY: ${GITHUB_ACTION_REPOSITORY}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: instamd-be-service
          cluster: InstaMD
          wait-for-service-stability: true
